#!/bin/bash
#检查系统服务是否正常运行
#
dir=/tmp/myscriptlog
t=`date "+%F %T"`
check_server ()
{
   p=`ps -C $1 --no-heading|wc -l`
   if [ $p -eq "0" ]
   then
      /etc/init.d/$1 start >/dev/null 2>$dir/check_server.err
      echo "$1 服务未启动，正在启动....重新启动时间：$t">>$dir/check_server.str
   else
      echo "$t $1 服务正常" >>$dir/check_server.log
   fi
}
check_server nginx
check_server mysqld
check_server squid
check_server zabbix_server
check_server zabbix_agentd
